### ISSUE TITLE
Tracking bug for dogfooding

### ISSUE THREAD

**Issue by cpcallen** [NeilFraser/CodeCity#233]
This bug tracks things that we must or should to do before beginning our initial dogfooding.

- [ ] Verify that we happy with version of server in use, and that no architectural changes affecting safe file format will be needed for minimum 3 months.
   - [ ] Create branch for (and tag this version) in GitHub, in case we need to reconstruct from repo + a `.city` file.
- [ ] Make sure checkpoints won't fill server persistent disk.
- [ ] Automate back-ups of prod server persistent disk (or at least `.city` files thereon).
